# 경로 설정
project_root: ${PWD}
source_dir: ${project_root}/src
config_dir: ${project_root}/configs
package_dir: ${source_dir}/anomaly_detection

# 외부 데이터 (절대 경로)
dataset_root: /mnt/d/deep_learning/datasets
mvtec_dir: ${dataset_root}/mvtec
visa_dir: ${dataset_root}/visa
btad_dir: ${dataset_root}/btad

# 백본 가중치 (절대 경로)
backbone_root: /mnt/d/deep_learning/backbones

# Output paths
output_root: ${project_root}/outputs
checkpoint_dir: ${output_root}/checkpoints
result_dir: ${output_root}/results
log_dir: ${output_root}/logs

# etc
experiment_dir: ${project_root}/experiments
notebook_dir: ${project_root}/notebooks
docs_dir: ${project_root}/docs