# configs/datasets/btad.yaml

name: btad
categories:
  - "01"
  - "02"
  - "03"

image_size: 256
normalization:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

train_split: train/ok
test_split: test
mask_split: ground_truth