# configs/datasets/visa.yaml

name: visa
categories:
  - candle
  - capsules
  - cashew
  - chewinggum
  - fryum
  - macaroni1
  - macaroni2
  - pcb1
  - pcb2
  - pcb3
  - pcb4
  - pipe_fryum

image_size: 256
normalization:
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]

split_ratio: 0.8
annotation_file: image_anno.csv